# Generated by Django 3.1.6 on 2021-03-03 07:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('altered', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='country_news/')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='country.country')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости стран',
            },
        ),
        migrations.CreateModel(
            name='CountryLeaderShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=150)),
                ('bitrhday', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=150)),
                ('assigned_degree', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='country_leader/')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_ships', to='country.country')),
            ],
            options={
                'verbose_name': 'Руководствы',
                'verbose_name_plural': 'Руководства',
            },
        ),
    ]
