# Generated by Django 3.1.6 on 2021-03-05 11:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('country', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryWinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=150)),
                ('bitrhday', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=150)),
                ('assigned_degree', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='country_winner/')),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='winner', to='country.country')),
            ],
            options={
                'verbose_name': 'Лучший игрок',
                'verbose_name_plural': 'Лучшие игроки',
            },
        ),
    ]
