# Generated by Django 3.1.6 on 2021-03-01 13:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('altered', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(upload_to='city_news/')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='city.city')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости городов',
            },
        ),
        migrations.CreateModel(
            name='CityLeaderShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=150)),
                ('bitrhday', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=150)),
                ('assigned_degree', models.DateField()),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='city_leader/')),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_ships', to='city.city')),
            ],
            options={
                'verbose_name': 'Лучший игрок',
                'verbose_name_plural': 'Лучшие игроки',
            },
        ),
    ]
