# Generated by Django 2.2.5 on 2021-04-15 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('city', '0002_auto_20210305_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='city',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='city',
            name='name_kz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='address_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='address_kz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='degree_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='degree_kz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='name_kz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='rank_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='cityleadership',
            name='rank_kz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citynews',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='citynews',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='citynews',
            name='title_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citynews',
            name='title_kz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='address_en',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='address_kz',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='degree_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='degree_kz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='description_en',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='description_kz',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='name_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='name_kz',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='rank_en',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AddField(
            model_name='citywinners',
            name='rank_kz',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
