# Generated by Django 3.1.6 on 2021-03-01 09:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
            ],
            options={
                'verbose_name': 'Страны',
                'verbose_name_plural': 'Страна',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='CountryLeaderShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=150)),
                ('bitrhday', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=150)),
                ('assigned_degree', models.DateField()),
                ('description', models.TextField()),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_ships', to='crud.country')),
            ],
            options={
                'verbose_name': 'Руководствы',
                'verbose_name_plural': 'Руководства',
            },
        ),
        migrations.CreateModel(
            name='CityLeaderShip',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150)),
                ('rank', models.CharField(max_length=150)),
                ('bitrhday', models.DateField()),
                ('address', models.CharField(max_length=250)),
                ('degree', models.CharField(max_length=150)),
                ('assigned_degree', models.DateField()),
                ('description', models.TextField()),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leader_ships', to='crud.city')),
            ],
            options={
                'verbose_name': 'Лучший игрок',
                'verbose_name_plural': 'Лучшие игроки',
            },
        ),
    ]
