# Generated by Django 3.1.6 on 2021-03-01 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CountryNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='crud/news/')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('altered', models.DateTimeField(auto_now=True)),
                ('country', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='crud.country')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости стран',
            },
        ),
        migrations.CreateModel(
            name='CityNews',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField()),
                ('image', models.ImageField(upload_to='crud/news/')),
                ('published', models.DateTimeField(auto_now_add=True)),
                ('altered', models.DateTimeField(auto_now=True)),
                ('city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to='crud.city')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости городов',
            },
        ),
    ]
