# Generated by Django 3.1.6 on 2021-03-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0002_citynews_countrynews'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='country',
            options={'ordering': ['name'], 'verbose_name': 'Страна', 'verbose_name_plural': 'Страны'},
        ),
    ]
