# Generated by Django 3.1.6 on 2021-03-01 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0003_auto_20210301_1609'),
    ]

    operations = [
        migrations.AddField(
            model_name='cityleadership',
            name='image',
            field=models.ImageField(default=None, upload_to='city_leader/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='countryleadership',
            name='image',
            field=models.ImageField(default=None, upload_to='country_leader/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='citynews',
            name='image',
            field=models.ImageField(upload_to='city_news/'),
        ),
        migrations.AlterField(
            model_name='countrynews',
            name='image',
            field=models.ImageField(upload_to='country_news/'),
        ),
    ]
