# Generated by Django 3.1.6 on 2021-03-01 10:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crud', '0004_auto_20210301_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cityleadership',
            name='bitrhday',
            field=models.DateField(default=datetime.date(1980, 1, 1)),
        ),
        migrations.AlterField(
            model_name='countryleadership',
            name='bitrhday',
            field=models.DateField(default=datetime.date(1980, 1, 1)),
        ),
    ]
